# Generated by Django 4.1.1 on 2022-09-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=100, verbose_name='著者')),
                ('author_eng', models.CharField(max_length=100, verbose_name='著者eng')),
                ('word_oder', models.CharField(choices=[('Aa', 'あ行'), ('Ka', 'か行'), ('Sa', 'さ行'), ('Ta', 'た行'), ('Na', 'な行'), ('Ha', 'は行'), ('Ma', 'ま行'), ('Ya', 'や行'), ('Ra', 'ら行'), ('Wa', 'わ行')], max_length=10, verbose_name='五十音')),
                ('age', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(blank=True, choices=[('', '未選択'), ('Mon', '男性'), ('Womon', '女性')], max_length=10, verbose_name='性別')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('contents_lite', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('action', 'アクション'), ('adventure', 'アドベンチャー'), ('youth', '青春'), ('love', '恋愛'), ('sf', 'SF'), ('history', '時代'), ('mystery', 'ミステリー'), ('comedy', 'コメディー'), ('horror', 'ホラー')], default=None, max_length=20, verbose_name='カテゴリー')),
                ('category_eng', models.CharField(blank=True, choices=[('action_eng', 'action'), ('adventure_eng', 'adventure'), ('youth_eng', 'youth'), ('love_eng', 'love'), ('sf_eng', 'sf'), ('history_eng', 'history'), ('mystery_eng', 'mystery'), ('comedy_eng', 'comedy'), ('horror_eng', 'horror')], max_length=20, null=True, verbose_name='カテゴリーeng')),
                ('color', models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('blue', 'blue'), ('pink', 'pink'), ('info', 'info'), ('green', 'green'), ('purple', 'purple'), ('warning', 'warning'), ('dark', 'dark')], max_length=20, verbose_name='色')),
                ('color_hex', models.CharField(blank=True, max_length=20, verbose_name='色_hex値')),
                ('contents', models.TextField(blank=True, verbose_name='コンテンツ')),
                ('contents_keyword', models.TextField(blank=True, verbose_name='キーワード')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('publisher_eng', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版社_eng')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('incorporated', models.DateField(verbose_name='設立日')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.TextField(verbose_name='目次')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100, verbose_name='シリーズ')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=20, verbose_name='ラベル')),
                ('label_eng', models.CharField(default=None, max_length=20, verbose_name='ラベルeng')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版者')),
            ],
        ),
    ]
