# Generated by Django 4.1.1 on 2022-09-18 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14, '文字数が一致していません。例）978-4167174033'), django.core.validators.RegexValidator('[0-9]{3}[-][0-9]{10}', '形式に当てはまっていません。例）978-4167174033')])),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('pages', models.SmallIntegerField(blank=True, null=True, verbose_name='ページ数')),
                ('issue', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('post_day', models.DateField(blank=True, null=True, verbose_name='投稿日')),
                ('update_day', models.DateField(blank=True, null=True, verbose_name='更新日')),
                ('youth_choices', models.CharField(choices=[('Y', 'Youth'), ('O', 'Old')], max_length=10, verbose_name='青春/白秋')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('contents_synopsis', models.TextField(blank=True, null=True, verbose_name='あらすじ')),
                ('fin', models.BooleanField(blank=True, null=True, verbose_name='完読')),
                ('amazon_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='アマゾンURL')),
                ('author_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者情報')),
                ('category_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='カテゴリー情報')),
                ('publisher_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版社情報')),
                ('publisher_label_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher_label', verbose_name='レーベル')),
                ('series_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='シリーズ情報')),
            ],
        ),
    ]
