# Generated by Django 4.1.1 on 2022-10-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_kindle_url_book_rakuten_kobo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品画像'),
        ),
    ]
