# Generated by Django 4.1.1 on 2022-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_book_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img_url',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品画像'),
        ),
    ]
