# Generated by Django 4.1.1 on 2022-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_inquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='ニックネーム'),
            preserve_default=False,
        ),
    ]
