# Generated by Django 4.1.1 on 2022-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_inquiry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry',
            field=models.TextField(max_length=2047, verbose_name='問い合わせ内容'),
        ),
    ]
