# Generated by Django 4.1.1 on 2022-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('post_day', models.DateField(blank=True, null=True, verbose_name='投稿日')),
            ],
        ),
    ]
