# Generated by Django 4.1.1 on 2022-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_other_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ'),
        ),
    ]
