# Generated by Django 4.1.1 on 2022-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_other_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='contents_synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='あらすじ'),
        ),
    ]
