# Generated by Django 4.1.1 on 2022-10-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_other_update_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='emb_instagram',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='instagram埋め込み'),
        ),
        migrations.AddField(
            model_name='book',
            name='emb_twitter',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='twitter埋め込み'),
        ),
    ]
