# Generated by Django 4.1.1 on 2023-01-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_other_fin_alter_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='アマゾンURL_text'),
        ),
    ]
